
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int RBRACK = 19;
  public static final int MOD = 9;
  public static final int MOD_ASSIGN = 14;
  public static final int IDENT = 27;
  public static final int SEMICOLON = 15;
  public static final int ELSE = 6;
  public static final int PLUS = 23;
  public static final int RBRACE = 21;
  public static final int RPAREN = 17;
  public static final int INT = 2;
  public static final int LBRACK = 18;
  public static final int RETURN = 4;
  public static final int INTCONST = 25;
  public static final int IF = 5;
  public static final int LBRACE = 20;
  public static final int LPAREN = 16;
  public static final int SUB = 7;
  public static final int EOF = 0;
  public static final int DIV = 8;
  public static final int PLUS_ASSIGN = 10;
  public static final int DOUBLECONST = 26;
  public static final int error = 1;
  public static final int ASSIGN = 22;
  public static final int MUL = 24;
  public static final int SUB_ASSIGN = 11;
  public static final int MUL_ASSIGN = 12;
  public static final int DIV_ASSIGN = 13;
  public static final int DOUBLE = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "DOUBLE",
  "RETURN",
  "IF",
  "ELSE",
  "SUB",
  "DIV",
  "MOD",
  "PLUS_ASSIGN",
  "SUB_ASSIGN",
  "MUL_ASSIGN",
  "DIV_ASSIGN",
  "MOD_ASSIGN",
  "SEMICOLON",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "ASSIGN",
  "PLUS",
  "MUL",
  "INTCONST",
  "DOUBLECONST",
  "IDENT"
  };
}

